-   id: clang-format
    name: clang-format
    entry: clang-format
    language: python
    'types_or': [c++, c, c#, java]
    args: ["-style=file", "-i"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: 2.9.2
